highlighter: rouge
markdown: kramdown
timezone: America/New_York
title: Slim Framework
url: http://www.slimframework.com
slim_version: v4
slim_docs_versions: v2, v3, v4
slim_website_repo: https://github.com/slimphp/Slim-Website/tree/gh-pages/
urlBasePath:
include: [.htaccess]
exclude: [node_modules]
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      docs-v4:
        - title: Get Started
          items:
          - [/docs/v4, Home]
          - [/docs/v4/start/installation.md, Installation]
          - [/docs/v4/start/upgrade.md, Upgrade Guide]
          - [/docs/v4/start/web-servers.md, Web Servers]
          - [/docs/v4/deployment/deployment.md, Deployment]
        - title: Tutorial
          items:
          - [/docs/v4/tutorial/first-app.md, First Application]

        - title: Concepts
          items:
          - [/docs/v4/concepts/value-objects.md, PSR 7]
          - [/docs/v4/concepts/middleware.md, Middleware]
          - [/docs/v4/concepts/di.md, Dependency Container]
        - title: The Application
          items:
          - [/docs/v4/objects/application.md, Overview]
        - title: The Request
          items:
          - [/docs/v4/objects/request.md, Overview]
          - [/docs/v4/objects/request.md#the-request-method, Method]
          - [/docs/v4/objects/request.md#the-request-headers, Headers]
          - [/docs/v4/objects/request.md#the-request-body, Body]
          - [/docs/v4/objects/request.md#uploaded-files, Uploaded Files]
          - [/docs/v4/objects/request.md#request-helpers, Helpers]
          - [/docs/v4/objects/request.md#route-object, Route object]
          - [/docs/v4/objects/request.md#media-type-parsers, Media type parsers]
        - title: The Response
          items:
          - [/docs/v4/objects/response.md, Overview]
          - [/docs/v4/objects/response.md#the-response-status, Status]
          - [/docs/v4/objects/response.md#the-response-headers, Headers]
          - [/docs/v4/objects/response.md#the-response-body, Body]
          - [/docs/v4/objects/response.md#returning-json, JSON]
        - title: Routing
          items:
          - [/docs/v4/objects/router.md, Overview]
          - [/docs/v4/objects/router.md#how-to-create-routes, Create Routes]
          - [/docs/v4/objects/router.md#route-callbacks, Callbacks]
          - [/docs/v4/objects/router.md#route-strategies, Strategies]
          - [/docs/v4/objects/router.md#route-placeholders, Placeholders]
          - [/docs/v4/objects/router.md#route-names, Names]
          - [/docs/v4/objects/router.md#route-groups, Groups]
          - [/docs/v4/objects/router.md#route-middleware, Middleware]
          - [/docs/v4/objects/router.md#router-caching, Caching]
          - [/docs/v4/objects/router.md#container-resolution, Container Resolution]
        - title: Packaged Middleware
          items:
          - [/docs/v4/middleware/routing.md, Routing]
          - [/docs/v4/middleware/error-handling.md, Error Handling]
          - [/docs/v4/middleware/method-overriding.md, Method Overriding]
          - [/docs/v4/middleware/output-buffering.md, Output Buffering]
          - [/docs/v4/middleware/content-length.md, Content Length]
        - title: Cook book
          items:
          - [/docs/v4/cookbook/route-patterns.md, Trailing / in routes]
          - [/docs/v4/cookbook/ip-address.md, Retrieving IP address]
          - [/docs/v4/cookbook/retrieving-current-route.md, Retrieving Current Route]
          - [/docs/v4/cookbook/database-eloquent.md, Using Eloquent with Slim]
          - [/docs/v4/cookbook/database-doctrine.md, Using Doctrine with Slim]
          - [/docs/v4/cookbook/database-atlas.md, Using Atlas with Slim]
          - [/docs/v4/cookbook/enable-cors.md, Enabling CORS]
          - [/docs/v4/cookbook/environment.md, Getting and Mocking the Environment]
          - [/docs/v4/cookbook/uploading-files.md, Uploading Files using POST forms]
          - [/docs/v4/cookbook/action-domain-responder.md, Action-Domain-Responder with Slim]
        - title: Add Ons
          items:
          - [/docs/v4/features/templates.md, Templates]
          - [/docs/v4/features/caching.md, HTTP Caching]
          - [/docs/v4/features/csrf.md, CSRF Protection]
          - [/docs/v4/features/flash.md, Flash Messages]

        - title: Contributing
          items:
          - [/docs/v3/contributors/strategy.md, Branching Strategy]
          - [/docs/v3/contributors/guidelines.md, Guidelines]

  - scope:
      path: "docs/v4"
      type: "pages"
    values:
      layout: docs-v4

  -
    scope:
      path: ""
      type: "pages"
    values:
      docs-v3:
        - title: Get Started
          items:
            - [/docs/v3, Home]
            - [/docs/v3/start/installation.md, Installation]
            - [/docs/v3/start/upgrade.md, Upgrade Guide]
            - [/docs/v3/start/web-servers.md, Web Servers]
            - [/docs/v3/deployment/deployment.md, Deployment]
        - title: Tutorial
          items:
            - [/docs/v3/tutorial/first-app.md, First Application]

        - title: Concepts
          items:
            - [/docs/v3/concepts/value-objects.md, PSR 7]
            - [/docs/v3/concepts/middleware.md, Middleware]
            - [/docs/v3/concepts/di.md, Dependency Container]
        - title: The Application
          items:
            - [/docs/v3/objects/application.md, Overview]
            - [/docs/v3/objects/application.md#application-configuration, Configuration]
            - [/docs/v3/objects/application.md#slim-default-settings, Default settings]
        - title: The Request
          items:
            - [/docs/v3/objects/request.md, Overview]
            - [/docs/v3/objects/request.md#the-request-method, Method]
            - [/docs/v3/objects/request.md#the-request-headers, Headers]
            - [/docs/v3/objects/request.md#the-request-body, Body]
            - [/docs/v3/objects/request.md#uploaded-files, Uploaded Files]
            - [/docs/v3/objects/request.md#request-helpers, Helpers]
            - [/docs/v3/objects/request.md#route-object, Route object]
            - [/docs/v3/objects/request.md#media-type-parsers, Media type parsers]
        - title: The Response
          items:
            - [/docs/v3/objects/response.md, Overview]
            - [/docs/v3/objects/response.md#the-response-status, Status]
            - [/docs/v3/objects/response.md#the-response-headers, Headers]
            - [/docs/v3/objects/response.md#the-response-body, Body]
            - [/docs/v3/objects/response.md#returning-json, JSON]
        - title: Routing
          items:
            - [/docs/v3/objects/router.md, Overview]
            - [/docs/v3/objects/router.md#how-to-create-routes, Create Routes]
            - [/docs/v3/objects/router.md#route-callbacks, Callbacks]
            - [/docs/v3/objects/router.md#route-strategies, Strategies]
            - [/docs/v3/objects/router.md#route-placeholders, Placeholders]
            - [/docs/v3/objects/router.md#route-names, Names]
            - [/docs/v3/objects/router.md#route-groups, Groups]
            - [/docs/v3/objects/router.md#route-middleware, Middleware]
            - [/docs/v3/objects/router.md#container-resolution, Container Resolution]
        - title: Error Handling
          items:
            - [/docs/v3/handlers/error.md, Error Handlers]
            - [/docs/v3/handlers/not-found.md, 404 Not Found]
            - [/docs/v3/handlers/not-allowed.md, 405 Not Allowed]
            - [/docs/v3/handlers/php-error.md, PHP Runtime Error]
        - title: Cook book
          items:
            - [/docs/v3/cookbook/route-patterns.md, Trailing / in routes]
            - [/docs/v3/cookbook/ip-address.md, Retrieving IP address]
            - [/docs/v3/cookbook/retrieving-current-route.md, Retrieving Current Route]
            - [/docs/v3/cookbook/database-eloquent.md, Using Eloquent with Slim]
            - [/docs/v3/cookbook/database-doctrine.md, Using Doctrine with Slim]
            - [/docs/v3/cookbook/database-atlas.md, Using Atlas with Slim]
            - [/docs/v3/cookbook/enable-cors.md, Enabling CORS]
            - [/docs/v3/cookbook/environment.md, Getting and Mocking the Environment]
            - [/docs/v3/cookbook/uploading-files.md, Uploading Files using POST forms]
            - [/docs/v3/cookbook/action-domain-responder.md, Action-Domain-Responder with Slim]
        - title: Add Ons
          items:
            - [/docs/v3/features/templates.md, Templates]
            - [/docs/v3/features/caching.md, HTTP Caching]
            - [/docs/v3/features/csrf.md, CSRF Protection]
            - [/docs/v3/features/flash.md, Flash Messages]
            - ['https://github.com/slimphp/Slim/wiki/Middleware-for-Slim-Framework-v3.x', 3rd Party]

        - title: Contributing
          items:
            - [/docs/v3/contributors/strategy.md, Branching Strategy]
            - [/docs/v3/contributors/guidelines.md, Guidelines]

  - scope:
      path: "docs/v3"
      type: "pages"
    values:
      layout: docs-v3

  -
    scope:
      path: ""
      type: "pages"
    values:
      docs-v2:
        - title: Get Started
          items:
            - [/docs/v2/index.md, Index]
            - [/docs/v2/start/get-started.md, Get Started]
        - title: Configuration
          items:
            - [/docs/v2/configuration/overview.md, Overview]
            - [/docs/v2/configuration/settings.md, Settings]
            - [/docs/v2/configuration/names-and-scopes.md, Names and Scopes]
            - [/docs/v2/configuration/modes.md, Modes]
        - title: Routing
          items:
            - [/docs/v2/routing/overview.md, Overview]
            - [/docs/v2/routing/get.md, GET Routes]
            - [/docs/v2/routing/post.md, POST Routes]
            - [/docs/v2/routing/put.md, PUT Routes]
            - [/docs/v2/routing/delete.md, DELETE Routes]
            - [/docs/v2/routing/options.md, OPTIONS Routes]
            - [/docs/v2/routing/patch.md, PATCH Routes]
            - [/docs/v2/routing/custom.md, Custom Routes]
            - [/docs/v2/routing/params.md, Parameters]
            - [/docs/v2/routing/names.md, Names]
            - [/docs/v2/routing/conditions.md, Conditions]
            - [/docs/v2/routing/middleware.md, Middleware]
            - [/docs/v2/routing/groups.md, Groups]
            - [/docs/v2/routing/helpers.md, Helpers]
            - [/docs/v2/routing/rewrite.md, URL Rewriting]
        - title: Environment
          items:
            - [/docs/v2/environment/overview.md, Overview]
        - title: Request
          items:
            - [/docs/v2/request/overview.md, Overview]
            - [/docs/v2/request/method.md, Method]
            - [/docs/v2/request/headers.md, Headers]
            - [/docs/v2/request/body.md, Body]
            - [/docs/v2/request/variables.md, Variables]
            - [/docs/v2/request/cookies.md, Cookies]
            - [/docs/v2/request/paths.md, Paths]
            - [/docs/v2/request/xhr.md, XHR]
            - [/docs/v2/request/helpers.md, Helpers]
            - [/docs/v2/request/content-types.md, Content-Types]
        - title: Response
          items:
            - [/docs/v2/response/overview.md, Overview]
            - [/docs/v2/response/status.md, Status]
            - [/docs/v2/response/headers.md, Headers]
            - [/docs/v2/response/body.md, Body]
            - [/docs/v2/response/cookies.md, Cookies]
            - [/docs/v2/response/helpers.md, Helpers]
        - title: View
          items:
            - [/docs/v2/view/overview.md, Overview]
            - [/docs/v2/view/rendering.md, Rendering]
            - [/docs/v2/view/custom.md, Custom]
            - [/docs/v2/view/data.md, Data]
        - title: HTTP Cache
          items:
            - [/docs/v2/cache/overview.md, Overview]
            - [/docs/v2/cache/etag.md, ETag]
            - [/docs/v2/cache/lastmodified.md, Last Modified]
            - [/docs/v2/cache/expires.md, Expires]
        - title: Middleware
          items:
            - [/docs/v2/middleware/overview.md, Overview]
            - [/docs/v2/middleware/how-to-use.md, How to Use]
            - [/docs/v2/middleware/how-to-write.md, How to Write]
        - title: Hooks
          items:
            - [/docs/v2/hooks/overview.md, Overview]
            - [/docs/v2/hooks/how-to-use.md, How to Use]
            - [/docs/v2/hooks/defaults.md, Defaults]
            - [/docs/v2/hooks/custom.md, Custom]
        - title: Flash Messages
          items:
            - [/docs/v2/flash/overview.md, Overview]
            - [/docs/v2/flash/next.md, Next]
            - [/docs/v2/flash/now.md, Now]
            - [/docs/v2/flash/keep.md, Keep]
        - title: Sessions
          items:
            - [/docs/v2/sessions/native.md, Native]
            - [/docs/v2/sessions/cookies.md, Cookies]
        - title: Logging
          items:
            - [/docs/v2/logging/overview.md, Overview]
            - [/docs/v2/logging/activate.md, Activate]
            - [/docs/v2/logging/levels.md, Levels]
            - [/docs/v2/logging/writers.md, Writers]
        - title: Error Handling
          items:
            - [/docs/v2/errors/overview.md, Overview]
            - [/docs/v2/errors/500.md, 500 System Error]
            - [/docs/v2/errors/404.md, 404 Not Found]
            - [/docs/v2/errors/debug.md, Debug Mode]
            - [/docs/v2/errors/output.md, Output]
        - title: Dependency Injection
          items:
            - [/docs/v2/di/overview.md, Overview]
  -
    scope:
      path: "docs/v2"
      type: "pages"
    values:
      layout: docs-v2
